// data.js — STEP 04・05・06 不定詞と動名詞マスター
const QUIZ_DATA = {
  frames: [
    { id: 'f026', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 026', tagClass: 'tag-f',
      question: "I've decided ( ) a lawyer.",
      options: ['becoming', 'become', 'became', 'to become'], answer: 3, source: '九州国際大',
      translation: '私は弁護士になることに決めた。',
      explanation: 'decideは動名詞ではなく不定詞を目的語にとる動詞なので，④to becomeを選ぶ。' },
    { id: 'f027', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 027', tagClass: 'tag-f',
      question: "I've finished ( ) the room, and I'm really hungry. What's for dinner?",
      options: ['cleaning', 'to clean', 'cleaned', 'being cleaned'], answer: 0, source: '法政大',
      translation: '私は部屋の掃除を終えて，本当にお腹がすいている。夕食は何？',
      explanation: 'finishは不定詞ではなく動名詞を目的語にとる動詞なので，①cleaningを選ぶ。' },
    { id: 'f028', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 028', tagClass: 'tag-f',
      question: 'Remember ( ) the door before you leave.',
      options: ['close', 'to close', 'closing', 'you close'], answer: 1, source: '玉川大',
      translation: '去る前に忘れずにドアを閉めなさい。',
      explanation: '「…することを覚えておく」という意味になるように，Rememberの目的語として不定詞②to closeを選ぶ。動名詞を目的語にとると「…したことを覚えている」という意味になるので，③closingは誤り。' },
    { id: 'f029', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 029', tagClass: 'tag-f',
      question: 'I want you ( ) English to communicate with the world.',
      options: ['learn', 'learned', 'learning', 'to learn'], answer: 3, source: '福井工業大',
      translation: '私はあなたに，世界中の人々と意思疎通を図るために英語を学んでもらいたい。',
      explanation: '〈want＋O＋to do〉の形で「Oが…することを望んでいる」の意味を表すので，④to learnを選ぶ。' },
    { id: 'f030', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 030', tagClass: 'tag-f',
      question: 'Mary saw a police officer ( ) the room.',
      options: ['enter', 'enters', 'to enter', 'have entered'], answer: 0, source: '梅花女子短大',
      translation: 'メアリーは警察官がその部屋に入るのを見た。',
      explanation: 'seeは感覚動詞。〈see＋O＋do〉の形をとるので，①enterを選ぶ。' },
    { id: 'f031', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 031', tagClass: 'tag-f',
      question: "Don't ( ) the students enter this room.",
      options: ['allow', 'let', 'permit', 'admit'], answer: 1, source: '十文字学園女子大',
      translation: '生徒をこの部屋に入れないようにしなさい。',
      explanation: '空所のあとに目的語と動詞の原形が続いていることに着目し，②letを選ぶ。〈let＋O＋do〉で「Oに…させてやる」という意味になる。' },
    { id: 'f032', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 032', tagClass: 'tag-f',
      question: 'It is natural ( ) babies to cry when they are hungry.',
      options: ['some', 'that', 'for', 'at'], answer: 2, source: '桜美林大',
      translation: '赤ちゃんがお腹がすいたときに泣くのは当然のことだ。',
      explanation: '文頭のItは形式主語で，真主語は不定詞to cry。不定詞の意味上の主語は〈for＋（代）名詞〉で表すので，③forを選ぶ。' },
    { id: 'f033', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 033', tagClass: 'tag-f',
      question: 'Jack had found ( ) hard to talk to Beth.',
      options: ['it', 'of', 'out', 'that'], answer: 0, source: '日本大',
      translation: 'ジャックは，ベスとは話しづらいと思っていた。',
      explanation: '形式目的語のitを用いて〈S＋V＋it＋C＋to do〉という形にすればよいので，①itを選ぶ。意味上の目的語はto talkである。' },
    { id: 'f034', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 034', tagClass: 'tag-f',
      question: 'I have nothing ( ). Will you lend me your pencil?',
      options: ['to write', 'to write with', 'to write for', 'to write by'], answer: 1, source: '中部大',
      translation: '私は書くためのものを何も持っていない。あなたの鉛筆を貸してもらえますか。',
      explanation: '不定詞がnothingを修飾する形にする。write with a pencilのように，「書くためのもの〔筆記具〕」を表すにはwithを用いるので，②to write withを選ぶ。' },
    { id: 'f035', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 035', tagClass: 'tag-f',
      question: 'Caesar entered the town ( ) that the enemy had fled already.',
      options: ['of finding', 'found', 'only to find', 'only to be found'], answer: 2, source: '関西学院大',
      translation: 'シーザーは町に入ったが，敵はすでに逃げてしまっていたのに気づいただけだった。',
      explanation: '「～，しかし結局…しただけのことだった」という意味を表す不定詞only to doの形，③only to findを選ぶ。この不定詞は結果を表す副詞用法。' },
    { id: 'f036', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 036', tagClass: 'tag-f',
      question: 'It is very kind ( ) you to give me a ride to the station.',
      options: ['of', 'for', 'to', 'in'], answer: 0, source: '東京造形大',
      translation: '駅まで私を車で送ってくださって，あなたはとても親切ですね。',
      explanation: 'kindのように人の性質・性格を表す形容詞では，判断の根拠を表す不定詞の意味上の主語は〈of＋人〉で表すので，①ofを選ぶ。' },
    { id: 'f037', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 037', tagClass: 'tag-f',
      question: 'Through this program we hope to persuade school children ( ) smoking or drugs.',
      options: ['to not try', 'not to try', 'try not to', 'try to not'], answer: 1, source: '関東学院大',
      translation: 'この番組を通して私たちは児童に喫煙やドラッグを試させないようにしたいと思う。',
      explanation: 'persuade O to doで「Oを説得して～させる」という意味を表し，否定語notを不定詞の直前に置いた形②not to tryを選ぶ。' },
    { id: 'f038', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 038', tagClass: 'tag-f',
      question: 'My father has just got home from Italy. He ( ) his trip very much.',
      options: ['seems to have enjoyed', 'has seemed to enjoy', 'seems to enjoy', 'seems to be enjoying'], answer: 0, source: '玉川大',
      translation: '私の父はイタリアからちょうど帰国したところだ。彼は旅をとても楽しんだようだ。',
      explanation: 'seem to doで「…するようだ」という意味を表す。「楽しんだようだ」と不定詞が述語動詞より以前の時を表すように，完了形の不定詞〈to have done〉の形になる①seems to have enjoyedを選ぶ。' },
    { id: 'f039', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 039', tagClass: 'tag-f',
      question: 'Mr. Thompson was ( ) to buy such an expensive car.',
      options: ['rich enough', 'too rich', 'so rich', 'less rich'], answer: 0, source: '名古屋経済大',
      translation: 'トンプソン氏はそんな高価な車を買えるほどお金持ちだった。',
      explanation: '〈形容詞＋enough to do〉の形で「～するほど…」の意味を表すので，①rich enoughを選ぶ。②too richだと「お金持ちすぎて買えなかった」となり意味が通らない。' },
    { id: 'f040', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 040', tagClass: 'tag-f',
      question: 'The trouble with you is that you do not know ( ) manage your time.',
      options: ['how do', 'how to', 'how do you', 'how you are'], answer: 1, source: '神奈川大',
      translation: 'あなたの問題点は，あなたは自分の時間の管理のしかたがわかっていないということだ。',
      explanation: 'knowの目的語となるように，how to doの形を用いて「どのように…すべきか〔…のしかた〕」という意味を表せばよいので，②how toを選ぶ。' },
    { id: 'f041', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 041', tagClass: 'tag-f',
      question: "Strange ( ), I didn't really enjoy the musical.",
      options: ['said', 'saying', 'to say', 'say'], answer: 2, source: '亜細亜大',
      translation: '不思議なことに，私はそのミュージカルはあまり楽しめなかった。',
      explanation: 'Strange to sayは「不思議なことに」という意味の慣用表現なので，③to sayを選ぶ。' },
    { id: 'f042', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 042', tagClass: 'tag-f',
      question: 'You should always remember to brush your teeth after ( ).',
      options: ['ate', 'eating', 'was eaten', 'have eaten'], answer: 1, source: '南山大',
      translation: '食事のあとは歯を磨くことを常に覚えておくべきだ。',
      explanation: '前置詞afterの目的語なので，動名詞の②eatingを選ぶ。' },
    { id: 'f043', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 043', tagClass: 'tag-f',
      question: 'My manager insists on ( ) the meeting in place of him.',
      options: ['me attend', 'me to attend', 'my attendance', 'my attending'], answer: 3, source: '立命館大',
      translation: '私の上司は，自分の代わりに私がその会議に出席することを強く求めている。',
      explanation: 'insist on ～で「～を強く求める」。前置詞onの目的語には動名詞がくる。動名詞の意味上の主語は所有格または目的格を直前に置くので，④my attendingを選ぶ。' },
    { id: 'f044', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 044', tagClass: 'tag-f',
      question: "I'm sorry for ( ) your email sooner.",
      options: ['not to answer', 'not having answered', 'not to have answer', 'no answering'], answer: 1, source: '桜美林大',
      translation: 'あなたのEメールに早くお返事しなかったことについて，おわびいたします。',
      explanation: '前置詞forの目的語なので動名詞が続く。動名詞を否定するnotは直前に置く。以前のことを表すには完了形の動名詞〈having done〉を用いるので，②not having answeredを選ぶ。' },
    { id: 'f045', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 045', tagClass: 'tag-f',
      question: 'She is not used to ( ) formal letters.',
      options: ['writing', 'write', 'writes', 'written'], answer: 0, source: '名古屋工業大',
      translation: '彼女は形式ばった手紙を書くことに慣れていない。',
      explanation: 'be used to doingで「…することに慣れている」という意味を表すので，①writingを選ぶ。' },
    { id: 'f046', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 046', tagClass: 'tag-f',
      question: 'She didn\'t mean to make him feel like ( ).',
      options: ['cried', 'cry', 'crying', 'to cry'], answer: 2, source: '立命館大',
      translation: '彼女は彼を泣きたい気持ちにさせるつもりはなかった。',
      explanation: 'feel like doingで「…したい気がする」という意味を表すので，③cryingを選ぶ。' },
    { id: 'f047', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 047', tagClass: 'tag-f',
      question: 'It is no ( ) crying over spilt milk.',
      options: ['while', 'time', 'help', 'use'], answer: 3, source: '九州国際大',
      translation: 'こぼれた牛乳を嘆いてもむだだ〔覆水盆に返らず〕。',
      explanation: 'It is no use doingで「…してもむだだ」という意味を表すので，④useを選ぶ。' },
    { id: 'f048', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 048', tagClass: 'tag-f',
      question: 'There is ( ) what will happen to us tomorrow.',
      options: ['no having told', 'no telling', 'not telling', 'not to tell'], answer: 1, source: 'センター試験',
      translation: '私たちに明日何が起こるかはわからない。',
      explanation: 'There is no doingで「…できない」という意味を表すので，②no tellingを選ぶ。' },
    { id: 'f049', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 049', tagClass: 'tag-f',
      question: 'My father received an email saying that Meg had succeeded in ( ) a new job.',
      options: ['find', 'to find', 'found', 'finding'], answer: 3, source: '広島工業大',
      translation: '父は，メグが新しい仕事をうまく見つけたと書いてあるEメールを受け取った。',
      explanation: 'succeed in doingで「…することに成功する／うまく…する」という意味を表すので，④findingを選ぶ。' },
    { id: 'f050', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 050', tagClass: 'tag-f',
      question: 'This bicycle needs ( ).',
      options: ['of fixing', 'being fixed', 'fixing', 'of being fixed'], answer: 2, source: '青山学院大',
      translation: 'この自転車は修理が必要だ。',
      explanation: 'needの目的語に動名詞がくると「…の必要がある」という意味を表すので，③fixingを選ぶ。' }
  ],
  exA: [
    { id: 'a01', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 01', tagClass: 'tag-a',
      question: "I've decided ( ) here. I'm tired.", options: ['stay', 'stayed', 'staying', 'to stay'], answer: 3, source: '金沢工業大',
      translation: '私はここにいることに決めた。疲れているので。', explanation: 'decideは動名詞ではなく不定詞を目的語にとる動詞なので，④to stayを選ぶ。' },
    { id: 'a02', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 02', tagClass: 'tag-a',
      question: 'Father promised ( ) his son to the zoo on Sunday.', options: ['taking', 'took', 'to take', 'have taken'], answer: 2, source: '立正大',
      translation: '父親は息子を，日曜日に動物園に連れて行くことを約束した。', explanation: 'promiseは動名詞ではなく不定詞を目的語にとる動詞なので，③to takeを選ぶ。' },
    { id: 'a03', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 03', tagClass: 'tag-a',
      question: "The doctor has advised me not to eat eggs anymore, so I've stopped ( ) them.", options: ['to have bought', 'buying', 'for buying', 'to buy'], answer: 1, source: '南山大',
      translation: '医師は私にもう卵を食べないようにと忠告している，だから私は買うのをやめた。', explanation: 'stopは不定詞ではなく動名詞を目的語にとる動詞なので，②buyingを選ぶ。stop to doは「…するために立ち止まる」という意味になるので，④to buyは不可。' },
    { id: 'a04', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 04', tagClass: 'tag-a',
      question: 'Have you finished ( ) your essay?', options: ['to write', 'writing', 'to have written', 'to be writing'], answer: 1, source: '明治大',
      translation: 'エッセイは書き終えましたか。', explanation: 'finishは不定詞ではなく動名詞を目的語にとる動詞なので，②writingを選ぶ。' },
    { id: 'a05', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 05', tagClass: 'tag-a',
      question: "I can't afford ( ) a new car.", options: ['to buying', 'to buy', 'buy', 'bought'], answer: 1, source: '福岡大',
      translation: '私は新しい車を買う余裕がない。', explanation: 'affordは動名詞ではなく不定詞を目的語にとる動詞なので，②to buyを選ぶ。afford to doで「…する余裕がある」という意味を表す。' },
    { id: 'a06', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 06', tagClass: 'tag-a',
      question: 'You had better avoid ( ) anything to embarrass your parents.', options: ['say', 'to say', 'saying', 'to have said'], answer: 2, source: '摂南大',
      translation: 'ご両親を困らせるようなことを言うのは避けたほうがいい。', explanation: 'avoidは不定詞ではなく動名詞を目的語にとる動詞なので，③sayingを選ぶ。avoid doingで「…するのを避ける」という意味を表す。' },
    { id: 'a07', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 07', tagClass: 'tag-a',
      question: "You ought to think about giving up ( ). It's bad for your health.", options: ['smoking', 'to smoke', 'smoke', 'being smoking'], answer: 0, source: '芝浦工業大',
      translation: 'あなたはタバコを吸うのをやめることを考えるべきだ。あなたの健康に悪いから。', explanation: 'give upは不定詞ではなく動名詞を目的語にとるので，①smokingを選ぶ。give up doingで「…するのをあきらめる，やめる」という意味を表す。' },
    { id: 'a08', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 08', tagClass: 'tag-a',
      question: 'Have you ever considered ( ) in Canada?', options: ['to work', 'being working', 'to be worked', 'working'], answer: 3, source: '甲南大',
      translation: 'カナダで働くことを考えたことがありますか。', explanation: 'considerは不定詞ではなく動名詞を目的語にとる動詞なので，④workingを選ぶ。②being workingは進行形の動名詞で，ここでは意味が成立しない。' },
    { id: 'a09', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 09', tagClass: 'tag-a',
      question: 'After a lot of problems she ( ) to learn to drive a car.', options: ['gave up', 'managed', 'put off', 'succeeded'], answer: 1, source: 'センター試験',
      translation: 'たくさんの問題のあと，彼女はどうにか車の運転を身につけた。', explanation: '空所のあとに不定詞が続いているので，不定詞を目的語にとる②managedを選ぶ。manage to doで「どうにか…する」という意味を表す。' },
    { id: 'a10', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 10', tagClass: 'tag-a',
      question: "I will never forget ( ) Paris last year. It was the best holiday I've ever had.", options: ['to visit', 'visit', 'visited', 'visiting'], answer: 3, source: '金沢工業大',
      translation: '私は昨年パリを訪れたことを決して忘れないだろう。それは私が経験した最高の休日だった。', explanation: '「…したことを忘れないだろう」という意味になるように，動名詞の④visitingを選ぶ。forget to doは「…することを忘れる」という意味であり，①to visitは不可。' },
    { id: 'a11', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 11', tagClass: 'tag-a',
      question: 'This story never ( ) to impress the audience.', options: ['sees', 'fails', 'makes', 'becomes'], answer: 1, source: '関西学院大',
      translation: 'この物語は必ず観客を感動させる。', explanation: '空所のあとに不定詞が続いているので，不定詞を目的語にとる②failsを選ぶ。fail to doで「…することを怠る／…しない」，never fail to doで「必ず…する」という意味になる。' },
    { id: 'a12', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 12', tagClass: 'tag-a',
      question: 'Please remember ( ) by his office before you go home.', options: ['having stopped', 'stop', 'to stopping', 'to stop'], answer: 3, source: '近畿大',
      translation: '帰宅する前に彼の会社に立ち寄ることを覚えておいてください。', explanation: '「…することを覚えておく」という意味になるように，rememberの目的語として不定詞④to stopを選ぶ。①having stoppedは「立ち寄っていたことを覚えておく」となり不可。' },
    { id: 'a13', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 13', tagClass: 'tag-a',
      question: 'I remember ( ) Manhattan on business as a young journalist.', options: ['to visit', 'visiting', 'visit', 'visited'], answer: 1, source: 'いわき明星大',
      translation: '私は若きジャーナリストとして仕事でマンハッタンを訪れたことを覚えている。', explanation: '「…したことを覚えている」という意味になるように，動名詞②visitingを選ぶ。不定詞を目的語にとると「（これから）訪れることを覚えておく」となり①to visitは不可。' },
    { id: 'a14', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 14', tagClass: 'tag-a',
      question: "Don't forget ( ) an appointment before you go to see the dentist.", options: ['making', 'to be making', 'to have been making', 'to make'], answer: 3, source: '京都産業大',
      translation: '歯医者に行く前には，予約をとることを忘れないように。', explanation: '「…することを忘れないように」という意味になるように，不定詞④to makeを選ぶ。動名詞を目的語にとると「…したことを忘れる」となるので①makingは不可。' },
    { id: 'a15', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 15', tagClass: 'tag-a',
      question: 'We tried ( ) on the door several times, but there was no answer.', options: ['knock', 'knocking', 'to knocking', 'have knocked'], answer: 1, source: '東京経済大',
      translation: '私たちは何度かドアをノックしたが，返事はなかった。', explanation: '「試しに…してみる」という意味になるように，動名詞②knockingを選ぶ。' },
    { id: 'a16', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 16', tagClass: 'tag-a',
      question: 'His grandfather wants ( ) study to become an engineer.', options: ['him that', 'he that', 'him to', 'to him'], answer: 2, source: '東洋大',
      translation: '彼の祖父は彼に，エンジニアになるために勉強してもらいたいと思っている。', explanation: '〈want＋O＋to do〉の形で「Oが…することを望んでいる」の意味を表すので，③him toを選ぶ。' },
    { id: 'a17', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 17', tagClass: 'tag-a',
      question: 'The doctor advised ( ) a complete rest.', options: ['her to take', 'her take', 'her taken', 'her taking'], answer: 0, source: '九州女子大',
      translation: '医師は彼女に，絶対安静にしているよう忠告した。', explanation: '〈advise＋O＋to do〉の形で「Oに…するように忠告する」の意味を表すので，①her to takeを選ぶ。' },
    { id: 'a18', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 18', tagClass: 'tag-a',
      question: 'We all tried to ( ) her to dance.', options: ['argue', 'persuade', 'claim', 'prevent'], answer: 1, source: '青山学院大',
      translation: '私たちはみんな彼女に踊るよう説得しようとした。', explanation: '〈persuade＋O＋to do〉の形で「Oを説得して…させる」の意味を表すので，②persuadeを選ぶ。try to doで「…しようとする」の意味を表す。' },
    { id: 'a19', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 19', tagClass: 'tag-a',
      question: 'Several people saw him ( ) the bag.', options: ['to be taken', 'take', 'to take', 'took'], answer: 1, source: '福岡大',
      translation: '彼がかばんを手に取るところを数人の人が見た。', explanation: 'sawは感覚動詞。〈see＋O＋do〉の形で「Oが…するのを見る」という意味になるので，②takeを選ぶ。' },
    { id: 'a20', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 20', tagClass: 'tag-a',
      question: 'I know the song very well because I often heard my father ( ) it.', options: ['sang', 'sung', 'sings', 'sing'], answer: 3, source: '金城学院大',
      translation: '父がその歌を歌うのをよく聞いたので，私はその歌をとてもよく知っている。', explanation: 'heardは感覚動詞。〈hear＋O＋do〉の形で「Oが…するのを聞く」という意味になるので，④singを選ぶ。' },
    { id: 'a21', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 21', tagClass: 'tag-a',
      question: "My mother wouldn't ( ) me eat more than one ice cream a day.", options: ['admit', 'get', 'let', 'permit'], answer: 2, source: '青山学院大',
      translation: '私の母はどうしても私に１日にアイスクリームを１つより多くは食べさせてくれない。', explanation: '空所のあとに目的語と動詞の原形が続いていることに着目し，③letを選ぶ。〈let＋O＋do〉で「Oに…させてやる」という意味になる。' },
    { id: 'a22', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 22', tagClass: 'tag-a',
      question: 'The ending of the movie was so touching that it made everyone ( ).', options: ['to cry', 'to crying', 'cry', 'in cry'], answer: 2, source: '北里大',
      translation: 'その映画の結末はとても感動的だったので，それでだれもが泣いた。', explanation: 'madeは使役動詞。〈make＋O＋do〉の形で「（強制的に）Oに…させる」という意味になるので，③cryを選ぶ。' },
    { id: 'a23', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 23', tagClass: 'tag-a',
      question: "I don't know how I can get my children ( ) their homework.", options: ['did', 'do', 'done', 'to do'], answer: 3, source: '南山大',
      translation: '私はどうやったら子どもたちに宿題をさせることができるのかわからない。', explanation: 'getは使役の意味を表すが，〈get＋O＋to do〉の形で「Oに…してもらう，させる」という意味を表すので，④to doを選ぶ。' },
    { id: 'a24', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 24', tagClass: 'tag-a',
      question: 'Because my mother was sick in bed, she had me ( ) the dishes after dinner.', options: ['wash', 'washed', 'have washed', 'to wash'], answer: 0, source: '成蹊大',
      translation: '私の母は病気で寝ていたので，夕食後彼女は私に皿洗いをさせた。', explanation: 'hadは使役動詞。〈have＋O＋do〉の形で「Oに…してもらう，させる」という意味になるので，①washを選ぶ。' },
    { id: 'a25', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 25', tagClass: 'tag-a',
      question: 'It is difficult ( ) the English exam.', options: ['in passing', 'to passed', 'to pass', 'pass'], answer: 2, source: '福岡大',
      translation: 'その英語の試験に受かるのは難しい。', explanation: '文頭のItは形式主語なので，真主語となる不定詞③to passを選ぶ。' },
    { id: 'a26', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 26', tagClass: 'tag-a',
      question: 'The young woman had no one ( ) with about her future.', options: ['to talk', 'talking', 'of talking', 'to have talked'], answer: 0, source: '獨協大',
      translation: 'その若い女性は自分の将来について話す相手がいなかった。', explanation: '不定詞がno oneを修飾する形になるように①to talkを選ぶ。現在分詞を用いると「～している…」の意味になるので②talkingは不可。' },
    { id: 'a27', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 27', tagClass: 'tag-a',
      question: 'Susan opened the box, ( ) to find it empty.', options: ['but', 'next', 'only', 'soon'], answer: 2, source: '立教大',
      translation: 'スーザンは箱を開けたが，それが空だということに気づいただけだった。', explanation: '不定詞only to doの形になるように，③onlyを選ぶ。この不定詞は結果を表す副詞用法。' },
    { id: 'a28', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 28', tagClass: 'tag-a',
      question: 'His grandfather lived ( ) ninety-two and was the head of the company for many years.', options: ['being', 'to be', 'for being', 'till he would be'], answer: 1, source: '東海大',
      translation: '彼の祖父は92歳まで生きて，長年，会社の社長だった。', explanation: '「その結果…する」という意味を表す不定詞②to beを選ぶ。' },
    { id: 'a29', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 29', tagClass: 'tag-a',
      question: 'It was careless ( ) him to forget to lock the door.', options: ['for', 'of', 'with', 'to'], answer: 1, source: '芝浦工業大',
      translation: 'ドアの鍵をかけ忘れるとは，彼は不注意だった。', explanation: 'carelessは人の性質・性格を表す形容詞であり，判断の根拠を表す不定詞の意味上の主語は〈of＋人〉で表すので，②ofを選ぶ。' },
    { id: 'a30', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 30', tagClass: 'tag-a',
      question: 'My friends were warned ( ) the mountain in such bad weather.', options: ['in climbing', 'not to climb', 'of no climbing', 'to climb'], answer: 1, source: 'センター試験',
      translation: '私の友人たちはそんな悪天候の中で登山しないようにと警告を受けた。', explanation: 'warn O to doで「Oに…するように警告する」。受動態で「登山しないように警告された」という意味になるように，否定語notを不定詞の直前に置いた②not to climbを選ぶ。' },
    { id: 'a31', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 31', tagClass: 'tag-a',
      question: 'Half of the houses on the island are said ( ) damaged by the typhoon.', options: ['having', 'to be being', 'to have', 'to have been'], answer: 3, source: '関東学院大',
      translation: 'その島の家々の半分が台風によって損壊したと言われている。', explanation: 'be said to doで「…すると言われている」。「損壊したと言われている」と完了形で受動態の不定詞になるように，④to have beenを選ぶ。' },
    { id: 'a32', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 32', tagClass: 'tag-a',
      question: 'The boy turned on his father\'s computer, though he had been told ( ).', options: ['not do it', 'not to', 'to do not', 'to not'], answer: 1, source: '青山学院大',
      translation: 'その男の子は父親のコンピュータの電源を入れた，そうしないようにと言われていたのだが。', explanation: 'told not to turn on … の内容を表すように，代不定詞のtoの前に否定語notを置いた形②not toを選ぶ。' },
    { id: 'a33', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 33', tagClass: 'tag-a',
      question: 'The textbook is ( ) for a college student to read.', options: ['easy enough', 'so easy as', 'so easy that', 'such easy'], answer: 0, source: '大妻女子大',
      translation: 'その教科書は大学生が読むのには十分やさしい。', explanation: '〈形容詞＋enough to do〉の形で「～するほど…」の意味を表すので①easy enoughを選ぶ。不定詞の意味上の主語は前に〈for＋（代）名詞〉を置く。' },
    { id: 'a34', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 34', tagClass: 'tag-a',
      question: "Mr. Smith doesn't know ( ) a computer and is afraid to touch one.", options: ['way to use', 'how he should to use', 'the way of use', 'how to use'], answer: 3, source: '東京経済大',
      translation: 'スミスさんはコンピュータの使い方がわからず，それを触るのも怖がっている。', explanation: 'how to doの形を用いて「…のしかた」という意味を表せばよいので，④how to useを選ぶ。' },
    { id: 'a35', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 35', tagClass: 'tag-a',
      question: "I can't decide ( ) go to Australia or New Zealand.", options: ['to if', 'whether', 'whether to', 'to whether'], answer: 2, source: '福岡大',
      translation: 'オーストラリアとニュージーランドのどちらに行こうか決められない。', explanation: 'decide to doで「…することを決める」。whether A or Bで「AとBのどちらか」となるので，③whether toを選ぶ。' },
    { id: 'a36', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 36', tagClass: 'tag-a',
      question: "To begin ( ), let's have a look at Chapter 5.", options: ['from', 'by', 'for', 'with'], answer: 3, source: '九州産業大',
      translation: 'まず初めに，第５章を見ましょう。', explanation: 'To begin withで「まず初めに」という意味の慣用表現なので，④withを選ぶ。' },
    { id: 'a37', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 37', tagClass: 'tag-a',
      question: 'To ( ) the truth, I still haven\'t finished my homework.', options: ['say', 'tell', 'speak', 'mention'], answer: 1, source: '大阪学院大',
      translation: '本当のことを言うと，私は宿題をまだ終えていない。', explanation: 'to tell the truthで「本当のことを言うと」という意味の慣用表現なので，②tellを選ぶ。' },
    { id: 'a38', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 38', tagClass: 'tag-a',
      question: '"I heard you were invited to the President\'s party." "Yes. I was surprised at how easy the President was ( )."', options: ['for talking', 'talking to', 'to talk', 'to talk to'], answer: 3, source: 'センター試験',
      translation: '「あなたは大統領のパーティーに招待されたと聞いたよ」「うん。大統領がどんなに話しやすい方かに驚いたよ」', explanation: 'the President was easy to talk toのeasyがhowとともに前に出たと考え，④to talk toを選ぶ。talk to the Presidentという関係なので③to talkは不可。' },
    { id: 'a39', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 39', tagClass: 'tag-a',
      question: 'The river is dangerous to ( ) in July.', options: ['being swum', 'swim in', 'swim it', 'swimming'], answer: 1, source: 'センター試験',
      translation: 'その川は７月に泳ぐには危険だ。', explanation: '形容詞dangerousを限定する不定詞「…するには」となるように，②swim inを選ぶ。swim in the riverという関係なのでinが必要。' },
    { id: 'a40', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 40', tagClass: 'tag-a',
      question: 'She went to France in ( ) to study French.', options: ['as', 'intention', 'order', 'spite'], answer: 2, source: '金城学院大',
      translation: '彼女はフランス語を勉強するためにフランスへ行った。', explanation: 'in order to doで「…するために」と目的を表すので，③orderを選ぶ。' },
    { id: 'a41', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 41', tagClass: 'tag-a',
      question: 'The girl was so kind ( ) me to the station.', options: ['as to take', 'of taking', 'in order to take', 'that it takes'], answer: 0, source: '日本女子大',
      translation: 'その女の子はとても親切で，私を駅まで連れて行ってくれた。', explanation: 'so ... as to doで「～するほど…／とても…なので～」という意味。①as to takeを選ぶ。' },
    { id: 'a42', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 42', tagClass: 'tag-a',
      question: 'The problem was ( ) difficult for him to solve.', options: ['too', 'to', 'two', 'so'], answer: 0, source: '神奈川工科大',
      translation: 'その問題は彼には難しすぎて解けなかった。', explanation: 'too ... to doで「とても…なので～できない」という意味を表すので，①tooを選ぶ。' },
    { id: 'a43', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 43', tagClass: 'tag-a',
      question: 'We talked quietly ( ) disturb him in his study.', options: ['not so as to', 'so not as to', 'so as not to', 'so as to no'], answer: 2, source: '奥羽大',
      translation: '私たちは勉強部屋にいる彼の邪魔にならないように静かに話をした。', explanation: 'so as not to doで「…しないように」という意味を表すので，③so as not toを選ぶ。' },
    { id: 'a44', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 44', tagClass: 'tag-a',
      question: "Ken obtained a driver's license before ( ) the university.", options: ['to enter', 'entering', 'his entrance', 'he had entering'], answer: 1, source: '東京経済大',
      translation: 'ケンは大学に入学する前に運転免許を取得した。', explanation: '前置詞beforeの目的語なので，動名詞②enteringを選ぶ。空所のあとに目的語となるthe universityが続いているので名詞③his entranceは不可。' },
    { id: 'a45', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 45', tagClass: 'tag-a',
      question: 'His doctor insists ( ) for a few days.', options: ['on he is resting', 'him on rest', 'on his resting', 'him resting'], answer: 2, source: '関東学院大',
      translation: '彼の医師は彼が数日間休養することを強く求めている。', explanation: 'insist on ～で「～を強く求める」。前置詞onの目的語には動名詞がくる。動名詞の主語は所有格または目的格を直前に置くので，③on his restingを選ぶ。' },
    { id: 'a46', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 46', tagClass: 'tag-a',
      question: '"Mother, this summer I want to travel abroad alone." "What? I can\'t agree to ( ) alone."', options: ['your travel', 'your traveling', 'you to travel', 'you to be traveled'], answer: 1, source: '北海学園大',
      translation: '「お母さん，この夏に私は１人で海外旅行したいの」「なんですって。あなたが１人で旅行することには賛成できないわ」', explanation: '前置詞toの目的語には動名詞がくる。動名詞の主語は所有格または目的格を直前に置くので，②your travelingを選ぶ。' },
    { id: 'a47', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 47', tagClass: 'tag-a',
      question: 'Some people showed up at the wedding party without ( ).', options: ['invited', 'being invited', 'they are invited', 'invite'], answer: 1, source: '東京経済大',
      translation: '招待されていないのに結婚パーティーに現れた人が何人かいた。', explanation: '前置詞withoutの目的語には動名詞がくる。主語のSome peopleが「招待される」という受け身の意味になるので，受動態の動名詞〈being done〉となる②being invitedを選ぶ。' },
    { id: 'a48', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 48', tagClass: 'tag-a',
      question: 'He repents of ( ) his studies in his school days.', options: ['having neglected', 'being neglected', 'having been neglected', 'neglecting in'], answer: 0, source: '東京電機大',
      translation: '彼は学生時代に学業をおろそかにしていたことを悔やんでいる。', explanation: '前置詞ofの目的語には動名詞がくる。以前のことを表すには完了形の動名詞〈having done〉を用いるので，①having neglectedを選ぶ。' },
    { id: 'a49', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 49', tagClass: 'tag-a',
      question: 'I ( ) the food in the university cafeteria.', options: ['used to eating', 'am used to eat', 'am used to eating', 'would use to eat'], answer: 2, source: '北里大',
      translation: '私は大学の食堂で食事をとるのに慣れている。', explanation: 'be used to doingで「…することに慣れている」という意味を表すので，③am used to eatingを選ぶ。' },
    { id: 'a50', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 50', tagClass: 'tag-a',
      question: "Though it's very cold tonight, do you feel like ( )?", options: ['go', 'to go', 'gone', 'going out'], answer: 3, source: '亜細亜大',
      translation: '今夜はとても寒いのに，あなたは外出したい気分なのですか。', explanation: 'feel like doingで「…したい気がする」という意味を表すので，④going outを選ぶ。' },
    { id: 'a51', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 51', tagClass: 'tag-a',
      question: 'There is no ( ) what will happen in the near future.', options: ['to know', 'knowing', 'known', 'knowingness'], answer: 1, source: '工学院大',
      translation: '近い将来何が起こるかを知ることはできない。', explanation: 'There is no doingで「…できない」という意味を表すので，②knowingを選ぶ。空所のあとに目的語となるwhat節が続いているので名詞④knowingnessは不可。' },
    { id: 'a52', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 52', tagClass: 'tag-a',
      question: 'It is no use ( ) her any advice.', options: ['by giving', 'give', 'giving', 'of giving'], answer: 2, source: '高岡法科大',
      translation: '彼女にどんな忠告をしてもむだだ。', explanation: 'It is no use doingで「…してもむだだ」という意味を表すので，③givingを選ぶ。' },
    { id: 'a53', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 53', tagClass: 'tag-a',
      question: 'My sister is looking forward ( ) abroad after graduation.', options: ['to go', 'going', 'go', 'to going'], answer: 3, source: '大阪産業大',
      translation: '私の姉〔妹〕は卒業後に外国に行くことを楽しみにしている。', explanation: 'look forward to doingで「…することを楽しみに待つ」という意味を表すので，④to goingを選ぶ。' },
    { id: 'a54', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 54', tagClass: 'tag-a',
      question: 'When it comes ( ), John is definitely the best in his class.', options: ['for jog', 'for jogging', 'to jog', 'to jogging'], answer: 3, source: '近畿大',
      translation: 'ジョギングということになると，ジョンが絶対にクラスでいちばんだ。', explanation: 'when it comes to doingで「話が～ということになると」という意味を表すので，④to joggingを選ぶ。' },
    { id: 'a55', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 55', tagClass: 'tag-a',
      question: "After visiting Los Angeles, I plan on ( ) in San Francisco for next month's meeting.", options: ['to staying', 'to stay', 'staying', 'stay'], answer: 2, source: '福岡大',
      translation: 'ロサンゼルスを訪問したあと，私は来月の会議のためにサンフランシスコにとどまるつもりだ。', explanation: 'plan on doingで「…するつもりである」という意味を表すので，③stayingを選ぶ。' },
    { id: 'a56', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 56', tagClass: 'tag-a',
      question: "This printer ( ). It doesn't work at all.", options: ['needs repairing', 'needs to repair', 'has to repair', 'must be repairing'], answer: 0, source: '東京経済大',
      translation: 'このプリンターは修理が必要だ。まったく作動しない。', explanation: '「プリンターは修理される」という受け身の関係に着目。need doingで「…される必要がある」という受動的な意味を表すので，①needs repairingを選ぶ。need to doは「…する必要がある」を表すので②は不可。' },
    { id: 'a57', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 57', tagClass: 'tag-a',
      question: 'I have a strong objection ( ) treated like this.', options: ['to be', 'to being', 'whether I am', 'whether I should be'], answer: 1, source: 'センター試験',
      translation: '私はこのように扱われることには断固抗議する。', explanation: 'objection to ～で「～への反対〔異議〕」を表し，前置詞toのあとには動名詞がくるので，②to beingを選ぶ。being treatedと受動態の動名詞になっている。' }
  ],
  exB: [
    { id: 'b01', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 01', tagClass: 'tag-b',
      question: 'If you are ①the kind of person who suffers ②from stress, you ③should consider ④to take more time to relax.',
      options: ['①', '②', '③', '④'], answer: 3, source: '南山大',
      spans: ['the', 'from', 'should', 'to take'],
      correction: '④ to take → taking', corrected: 'If you are the kind of person who suffers from stress, you should consider taking more time to relax.',
      translation: 'あなたがストレスを受けやすいタイプの人なら，リラックスする時間をもっととることを考えるべきだ。',
      explanation: 'considerは不定詞ではなく動名詞を目的語にとる動詞。④to takeは動名詞takingにする。' },
    { id: 'b02', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 02', tagClass: 'tag-b',
      question: '①Sometimes students avoid ②to look at the teacher ③if they ④don\'t know the answer.',
      options: ['①', '②', '③', '④'], answer: 1, source: '文化女子大',
      spans: ['Sometimes', 'to look', 'if', 'don\'t'],
      correction: '② to look → looking', corrected: 'Sometimes students avoid looking at the teacher if they don\'t know the answer.',
      translation: '時々生徒たちは答えがわからないと先生を見るのを避ける。',
      explanation: 'avoidは不定詞ではなく動名詞を目的語にとる動詞。②to lookは動名詞lookingにする。' },
    { id: 'b03', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 03', tagClass: 'tag-b',
      question: '①Computers allow engineers ②testing ③dozens of options without ④producing expensive models.',
      options: ['①', '②', '③', '④'], answer: 1, source: '北里大',
      spans: ['Computers', 'testing', 'dozens', 'producing'],
      correction: '② testing → to test', corrected: 'Computers allow engineers to test dozens of options without producing expensive models.',
      translation: 'コンピュータのおかげでエンジニアはお金のかかる模型を作らずに多くの選択肢を試すことができる。',
      explanation: '〈allow＋O＋to do〉の形で「Oが…するのを許す」という意味を表すので，②testingは不定詞to testにする。' },
    { id: 'b04', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 04', tagClass: 'tag-b',
      question: 'Although we are ①concerned with the problem of energy ②sources, we ③must not fail ④recognizing the need for environmental protection.',
      options: ['①', '②', '③', '④'], answer: 3, source: '明治学院大',
      spans: ['concerned with', 'sources', 'must not fail', 'recognizing'],
      correction: '④ recognizing → to recognize', corrected: 'Although we are concerned with the problem of energy sources, we must not fail to recognize the need for environmental protection.',
      translation: '私たちはエネルギー源の問題に関心があるけれども，環境保全の必要性を認識することを怠ってはならない。',
      explanation: 'fail to doの形で「…することを怠る／…しない」という意味を表すので，④recognizingは不定詞to recognizeにする。' },
    { id: 'b05', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 05', tagClass: 'tag-b',
      question: 'I remember ①sit at the kitchen table in our Kuala Lumpur home ②when I was eight, ③watching my mother ④fix dinner.',
      options: ['①', '②', '③', '④'], answer: 0, source: '明治学院大',
      spans: ['sit', 'when', 'watching', 'fix'],
      correction: '① sit → sitting', corrected: 'I remember sitting at the kitchen table in our Kuala Lumpur home when I was eight, watching my mother fix dinner.',
      translation: '私は８歳のときに母が夕食を作るのを見ながら，クアラルンプールの家の食卓についていたことを覚えている。',
      explanation: 'remember doingで「…したことを覚えている」という意味を表すので，①sitは動名詞sittingにする。〈watch＋O＋do〉は「Oが…するのを見守る」という意味を表す。' },
    { id: 'b06', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 06', tagClass: 'tag-b',
      question: 'An experiment is now under way in Hokkaido ①to test the effects of using snow ②to keep food fresh for a long period. Crops are believed ③to increase their sweetness when ④to preserve in snow.',
      options: ['①', '②', '③', '④'], answer: 3, source: '桜美林大',
      spans: ['to test', 'to keep', 'to increase', 'to preserve'],
      correction: '④ to preserve → preserved', corrected: 'Crops are believed to increase their sweetness when preserved in snow.',
      translation: '長い期間食物を新鮮に保つために雪を利用することの効果を調べる実験が，今北海道で行われている。農作物は雪の中で保存されるとその甘みを増すと信じられている。',
      explanation: 'whenのあとにto preserveを続けても意味をなさない。「農作物が雪の中で保存される」という受け身の意味になるように，when (crops are) preservedとし，④to preserveを過去分詞preservedにする。' },
    { id: 'b07', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 07', tagClass: 'tag-b',
      question: 'It ①is up to the organizers of the concert to decide ②whether or not give profits ③from the concert to victims of ④the recent flood.',
      options: ['①', '②', '③', '④'], answer: 1, source: '立命館大',
      spans: ['is up to', 'whether or not give', 'from the concert', 'the recent flood'],
      correction: '② whether or not give → whether or not to give', corrected: 'It is up to the organizers of the concert to decide whether or not to give profits from the concert to victims of the recent flood.',
      translation: '最近起こった水害の被災者に，コンサートの利益を贈るかどうか決めるのは，コンサートの主催者次第である。',
      explanation: 'decide to doで「…することに決める」という意味を表すので，②whether or not giveはwhether or not to giveにする。' },
    { id: 'b08', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 08', tagClass: 'tag-b',
      question: 'It ①is clear to me that John is ②enough experienced to be given ③more responsibility ④for product development.',
      options: ['①', '②', '③', '④'], answer: 1, source: '早稲田大',
      spans: ['is clear to', 'enough experienced', 'more responsibility', 'for product development'],
      correction: '② enough experienced → experienced enough', corrected: 'It is clear to me that John is experienced enough to be given more responsibility for product development.',
      translation: 'ジョンは商品開発に対する責任をもっと与えられてもいいほど十分ベテランだということは，私には明らかだ。',
      explanation: '〈形容詞＋enough to do〉の語順で「～するほど…」の意味を表すので，②enough experiencedはexperienced enoughにする。' },
    { id: 'b09', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 09', tagClass: 'tag-b',
      question: 'Nancy was ①so happy ②that she felt like ③to sing ④a song.',
      options: ['①', '②', '③', '④'], answer: 2, source: '東洋大',
      spans: ['so happy', 'that', 'to sing', 'a song'],
      correction: '③ to sing → singing', corrected: 'Nancy was so happy that she felt like singing a song.',
      translation: 'ナンシーはとてもうれしかったので，歌を歌いたい気分になった。',
      explanation: 'feel like doingで「…したい気がする」という意味を表すので，③to singはsingingにする。' },
    { id: 'b10', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 10', tagClass: 'tag-b',
      question: '①The teacher ②criticized her for ③make ④the same mistake again and again.',
      options: ['①', '②', '③', '④'], answer: 2, source: '立命館大',
      spans: ['The', 'criticized', 'make', 'the same'],
      correction: '③ make → making', corrected: 'The teacher criticized her for making the same mistake again and again.',
      translation: '先生は彼女が何度も同じ間違いをするので非難した。',
      explanation: '前置詞forの目的語なので，③makeは動名詞makingにする。' },
    { id: 'b11', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 11', tagClass: 'tag-b',
      question: "Mrs. Smith in the administration can ①be relied upon when it comes ②in handling students' problems because she has ③a lot of experience as a counselor at ④a boys' high school.",
      options: ['①', '②', '③', '④'], answer: 1, source: '杏林大',
      spans: ['be relied upon', 'in handling', 'a lot of experience', 'a boys\' high school'],
      correction: '② in handling → to handling', corrected: "Mrs. Smith in the administration can be relied upon when it comes to handling students' problems because she has a lot of experience as a counselor at a boys' high school.",
      translation: '事務局のスミスさんは学生の問題を扱うこととなると信頼できる人だ。というのも，彼女は男子高校で，カウンセラーとして豊富な経験があるからだ。',
      explanation: 'when it comes to doingで「話が～ということになると」という意味を表すので，②in handlingはto handlingとする。' }
  ],
  exC: [
    { id: 'c01', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 01', tagClass: 'tag-c',
      japanese: '暗くなる前に必ず戻って来なさい。', prefix: "Don't", suffix: 'gets dark.',
      words: ['to', 'it', 'before', 'back', 'come', 'forget'], note: null, source: 'つくば国際大',
      answer: "Don't forget to come back before it gets dark.",
      explanation: '「必ず…しなさい」は「…することを忘れないようにしなさい」と言いかえる。forget to doで「…することを忘れる」を表すので，forget to come backと続ける。' },
    { id: 'c02', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 02', tagClass: 'tag-c',
      japanese: '車で駅まで送って行こうか。', prefix: 'Do', suffix: 'to the station?',
      words: ['drive', 'you', 'me', 'to', 'want', 'you'], note: null, source: '大阪電気通信大',
      answer: 'Do you want me to drive you to the station?',
      explanation: '〈want＋O＋to do〉の形で「Oが…することを望んでいる」の意味を表すので，Do you want me to driveと続ける。' },
    { id: 'c03', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 03', tagClass: 'tag-c',
      japanese: '医学の進歩により，人々はより長生きできるようになった。', prefix: '', suffix: '.',
      words: ['to', 'people', 'live', 'enabled', 'have', 'longer', 'medical advancements'], note: null, source: '酪農学園大',
      answer: 'Medical advancements have enabled people to live longer.',
      explanation: '〈enable＋O＋to do〉で「Oが…するのを可能にする」という意味を表すので，主語にMedical advancementsを置き，have enabled people to ...とつなげる。' },
    { id: 'c04', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 04', tagClass: 'tag-c',
      japanese: 'スーザンに言われてピーターは決心を変えた。', prefix: '', suffix: '.',
      words: ['because', 'caused', 'change', 'his', 'mind', 'Peter', "Susan's", 'to', 'words'], note: '1語不要', source: '東京理科大',
      answer: "Susan's words caused Peter to change his mind.",
      explanation: '〈cause＋O＋to do〉で「Oが…する原因となる」という意味を表すので，Susan\'s words caused Peter to ...とつなげる。becauseが不要。' },
    { id: 'c05', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 05', tagClass: 'tag-c',
      japanese: '先生は最初の授業でお互いのことがわかるように，生徒たちに自己紹介をさせた。', prefix: '', suffix: 'get to know each other in the first class.',
      words: ['the students', 'themselves', 'introduce', 'made', 'to', 'the teacher'], note: null, source: '芝浦工業大',
      answer: 'The teacher made the students introduce themselves to get to know each other in the first class.',
      explanation: 'madeは使役動詞で，〈make＋O＋do〉で「Oに…させる」という意味になる。introduce oneselfで「自己紹介する」。' },
    { id: 'c06', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 06', tagClass: 'tag-c',
      japanese: '初めのうち，私は新しい生活になかなかなじめなかった。', prefix: 'At first, I', suffix: 'to my new life.',
      words: ['to', 'get', 'difficult', 'it', 'used', 'found'], note: null, source: '埼玉医科大',
      answer: 'At first, I found it difficult to get used to my new life.',
      explanation: 'itを形式目的語として〈S＋V＋it＋C＋to do〉という形にする。get used to ～で「～に慣れる」という意味を表す。' },
    { id: 'c07', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 07', tagClass: 'tag-c',
      japanese: 'この家は私たちが住めるだけの広さがある。', prefix: 'This house is', suffix: '.',
      words: ['enough', 'for', 'in', 'large', 'us', 'live', 'to'], note: null, source: '東洋大',
      answer: 'This house is large enough for us to live in.',
      explanation: '〈形容詞＋enough to do〉の形で「～するほど…」の意味を表す。live in this houseの関係なので，to liveのあとにinを置く。' },
    { id: 'c08', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 08', tagClass: 'tag-c',
      japanese: 'せっかくフォード氏のオフィスに行ったのに，彼はすでに立ち去ったあとだった。', prefix: "I went to Mr. Ford's office", suffix: '.',
      words: ['find', 'had left', 'he', 'only', 'that', 'to'], note: null, source: '近畿大',
      answer: "I went to Mr. Ford's office only to find that he had left.",
      explanation: 'only to doで「～，しかし結局…しただけのことだった」という意味を表すので，only to findとつなげ，findの目的語となるthat節を置く。' },
    { id: 'c09', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 09', tagClass: 'tag-c',
      japanese: '一言も聞き漏らさないように，スミス教授の説明を注意深く聞きました。', prefix: 'I listened to Professor Smith carefully', suffix: 'a single word.',
      words: ['as', 'miss', 'so', 'to', 'not'], note: null, source: '明海大',
      answer: 'I listened to Professor Smith carefully so as not to miss a single word.',
      explanation: 'so as not to doで「…しないように」という意味を表す。' },
    { id: 'c10', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 10', tagClass: 'tag-c',
      japanese: '私は彼女とそれについて話し合う機会がなかった。', prefix: 'I had', suffix: 'her.',
      words: ['opportunity', 'no', 'it', 'to', 'discuss', 'with'], note: null, source: '東京歯科大',
      answer: 'I had no opportunity to discuss it with her.',
      explanation: 'hadの目的語にno opportunityを置き，これを修飾する形容詞用法の不定詞to discussを続ける。discuss ～ with ...で「～について…と話し合う」という意味になる。' },
    { id: 'c11', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 11', tagClass: 'tag-c',
      japanese: 'ミラーさんは，自分の息子は英語を勉強することが大切だと思った。', prefix: 'Mr. Miller', suffix: '.',
      words: ['it', 'for his son', 'important', 'to study English', 'thought'], note: null, source: '関東学院大',
      answer: 'Mr. Miller thought it important for his son to study English.',
      explanation: 'itを形式目的語として〈S＋V＋it＋C＋to do〉という形にする。不定詞の意味上の主語は〈for＋（代）名詞〉を不定詞の前に置いて表す。' },
    { id: 'c12', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 12', tagClass: 'tag-c',
      japanese: '彼はチケット売り場に早く着いたけれども，ショーのチケットはすべてすでに売り切れてしまったと言われただけだった。', prefix: 'He arrived early at the ticket office only', suffix: 'for the show had already been sold out.',
      words: ['to be', 'that', 'the tickets', 'told', 'all'], note: null, source: 'センター試験',
      answer: 'He arrived early at the ticket office only to be told that all the tickets for the show had already been sold out.',
      explanation: 'only to doで「～，しかし結局…しただけのことだった」を表すのでonly to beとし，toldを続けて受動態の不定詞にする。そのあとに目的語となるthat節を続ける。' },
    { id: 'c13', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 13', tagClass: 'tag-c',
      japanese: '泥棒は侵入した際にまったく指紋を残さないように手袋をはめていたようだ。', prefix: "The police haven't found any clues. The thief seems to have", suffix: 'any fingerprints when he broke in.',
      words: ['gloves', 'in order', 'not', 'to leave', 'worn'], note: null, source: 'センター試験',
      answer: "The police haven't found any clues. The thief seems to have worn gloves in order not to leave any fingerprints when he broke in.",
      explanation: 'seem to have doneで「…したようだ」という意味になる。in order not to doで「…しないように」という意味を表す。' },
    { id: 'c14', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 14', tagClass: 'tag-c',
      japanese: '彼を説得してその仕事をさせようとしてもむだだ。（言い換え）', prefix: 'It is', suffix: 'trying to persuade him to do the work.',
      words: ['no', 'use'], note: '同意文の空所補充', source: '愛媛大',
      answer: 'It is no use trying to persuade him to do the work.',
      explanation: 'It is no use doingで「…してもむだだ」という意味を表すので，no useを入れる。' },
    { id: 'c15', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 15', tagClass: 'tag-c',
      japanese: '私たちは，事実を否定することはできないと思った。（言い換え）', prefix: 'We thought that there was no', suffix: 'the fact.',
      words: ['denying'], note: '同意文の空所補充', source: '崇城大',
      answer: 'We thought that there was no denying the fact.',
      explanation: 'There is no doingで「…できない」という意味を表すので，denyingを入れる。' },
    { id: 'c16', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 16', tagClass: 'tag-c',
      japanese: 'あなたのシャツは繕う必要がある。（言い換え）', prefix: 'Your shirt', suffix: 'mending.',
      words: ['needs'], note: '同意文の空所補充', source: '愛媛大',
      answer: 'Your shirt needs mending.',
      explanation: 'need doingで「…の必要がある」という意味を表すので，needsを入れる。（have＋O＋doneの言い換え）' },
    { id: 'c17', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 17', tagClass: 'tag-c',
      japanese: '彼は若いとき怠慢であったことを悔やんでいる。', prefix: 'He', suffix: 'in his youth.',
      words: ['lazy', 'regrets', 'having', 'been'], note: null, source: '九州産業大',
      answer: 'He regrets having been lazy in his youth.',
      explanation: '「…したことを後悔する」はregret doingで表す。「怠慢であった」のは「悔やんでいる」よりも以前のことなので，完了形の動名詞having been lazyとする。' },
    { id: 'c18', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 18', tagClass: 'tag-c',
      japanese: '新しくできた公園を散歩するのはどうですか。', prefix: '', suffix: 'taking a walk in the new park?',
      words: ['to', 'do', 'say', 'you', 'what'], note: null, source: '明海大',
      answer: 'What do you say to taking a walk in the new park?',
      explanation: '「…するのはどうですか」はWhat do you say to doing?で表せる。' },
    { id: 'c19', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 19', tagClass: 'tag-c',
      japanese: 'まだひとり暮らしをするのに慣れていない。', prefix: "I'm still not", suffix: '.',
      words: ['to', 'by', 'living', 'myself', 'used'], note: null, source: '玉川大',
      answer: "I'm still not used to living by myself.",
      explanation: 'be used to doingで「…することに慣れている」という形にする。' },
    { id: 'c20', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 20', tagClass: 'tag-c',
      japanese: '原子力は有用なエネルギーであるが，常に我々の恐怖感がともなっていることは否定できない。', prefix: 'Nuclear energy is a useful energy resource, but', suffix: 'with our fears.',
      words: ['always associated', 'denying', 'it is', 'no', 'that', 'there is'], note: null, source: '近畿大',
      answer: 'Nuclear energy is a useful energy resource, but there is no denying that it is always associated with our fears.',
      explanation: '「…できない」はthere is no doingで表せるのでthere is no denyingと組み立て，that it is always associated with ～を続ける。' },
    { id: 'c21', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 21', tagClass: 'tag-c',
      japanese: '私は朝食に甘いものは何も食べる気がしない。', prefix: "I don't", suffix: 'breakfast.',
      words: ['like', 'feel', 'sweet', 'for', 'anything', 'having'], note: null, source: '西南学院大',
      answer: "I don't feel like having anything sweet for breakfast.",
      explanation: 'feel like doingで「…したい気がする」の形にする。' },
    { id: 'c22', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 22', tagClass: 'tag-c',
      japanese: '同じ仕事をするのであれば，女性に男性よりも少なく支払うもっともな理由はない。', prefix: 'There is no good reason for', suffix: 'job.',
      words: ['if', 'less than men', 'paying women', 'the same', 'they do'], note: null, source: 'センター試験',
      answer: 'There is no good reason for paying women less than men if they do the same job.',
      explanation: '前置詞forのあとに動名詞句paying womenを続け，less than menで女性と男性を比較する。残った語でif節を組み立てる。' },
    { id: 'c23', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 23', tagClass: 'tag-c',
      japanese: '彼の話を感動して泣かずに聞いた者は部屋にだれもいなかった。', prefix: 'Mike talked about his sad experience. Nobody in the room', suffix: 'to tears.',
      words: ['being', 'his story', 'moved', 'without', 'heard'], note: null, source: 'センター試験',
      answer: 'Mike talked about his sad experience. Nobody in the room heard his story without being moved to tears.',
      explanation: '主語Nobody in the roomに述語動詞heardと目的語his storyを続け，without doingで「…することなしに」を続ける。be moved to tearsで「感動して涙を流す」という意味になる。' }
  ]
};

const EIGO_SENTENCES = [];
